export const navLinks = [
  { href: "/login", label: "Log in" },
  { href: "/register", label: "Register" },
  { href: "/about", label: "About" },
  { href: "/book", label: "About book" },
  { href: "/shiassistant", label: "Shi assistant" },
  { href: "/tools", label: "Tools" },
  { href: "/study", label: "Study" },
  { href: "/blog", label: "Blog / News" },
  { href: "/community", label: "Community" },
  { href: "/checklist", label: "Check-List" },
  { href: "/team", label: "Team" },
  { href: "/resources", label: "Resources" },
  { href: "/profile", label: "Profile" },
  { href: "/calendar", label: "Calendar" },
  { href: "/setting", label: "setting" },
];
